server:
  port: ${PORT:9080}

spring:
  application:
    name: ${SERVICE_NAME:test-education-project}
  jpa:
    show-sql: true

notification:
  telegram: false

logging:
  level:
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}
