server:
  port: ${PORT:9080}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
  application:
    name: ${SERVICE_NAME:test-education-project}
  datasource:
    url: jdbc:postgresql://localhost:5432/solarl
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false

telegram:
  bot:
    username: "AcademyNotificationBot"
    token: ""
    chat-id: ""  # ID чата, куда отправлять сообщения

keycloak:
  realm: master
  auth-server-url: http://localhost:8080
  resource: avito
  public-client: true
  bearer-only: true


logging:
  level:
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}
