name: Build and Test

on:
  push:
    branches:
      - release*
  pull_request:
    branches:
      - release*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Установка JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Шаг 3: Кэширование зависимостей Gradle
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Шаг 4: Сборка проекта
      - name: Build project
        run: ./gradlew.sh build --no-daemon

      # Шаг 5: Запуск тестов
      - name: Run tests
        run: ./gradlew.sh test --no-daemon
